title = "AdGoBye Ads"
description = "Base Ads Blocklist made by AGB Team"
maintainer = "https://zombo.com"

[[block]]
friendly_name = "LSMedia"
world_id = "wrld_f767d1c8-b249-4ecc-a56f-614e433682c8"
game_objects = [{ name = "ADs" }]

[[block]]
friendly_name = "Popcorn Palace"
world_id = "wrld_266523e8-9161-40da-acd0-6bd82e075833"
game_objects = [
    { name = "PosterManager" },
    { name = "PhotoViewer" },
    { name = "PhotoViewer (1)" },
    { name = "PhotoViewer (2)" },
    { name = "PhotoViewer (3)" }
]

[[block]]
friendly_name = "Sovren's Chill home"
world_id = "wrld_1b482eca-bede-4de8-88a8-bbb6ca7e24cd"
game_objects = [
    { name = "add board" },
    { name = "InsetPosterDarkVerticalBlack_04" }
]

[[block]]
friendly_name = "SunDown"
world_id = "wrld_c54add9f-29b2-4b60-b051-e4999966ebc8"
game_objects = [{ name = "Promotional" }]

[[block]]
friendly_name = "Midnight Rooftop"
world_id = "wrld_d29bb0d0-d268-42dc-8365-926f9d485505"
game_objects = [
    # Branding on the poor dog, the Nevermet marketing team needs less crack
    { name = "logo 400x400 (1)"},
    { name = "NeverMetLogoFixedWhite"},
    
    { name = "Nevermet Billboard" },
    { name = "Billboard Downloader - Nevermet"}, # probably overkill but let's do it anyway
    { name = "SpawnPosters Downloader" }
]

[[block]]
friendly_name = "Furry Hideout"
world_id = "wrld_4b341546-65ff-4607-9d38-5b7f8f405132"
game_objects = [
    { name = "MeshBaker (0)-mesh-mesh (2)", position = { x = 47.523617, y = -116.42, z = -118 } },
    { name = "MeshBaker (0)-mesh-mesh", position = { x = 24.88094, y = -46.38, z = 1.1399894 } },
    { name = "MeshBaker (0)-mesh-mesh (1)", position = { x = 176.88394, y = 56.295246, z = -273.913 } },
    { name = "Cube (9)" }
]

[[block]]
friendly_name = "Prison Escape!"
world_id = "wrld_14750dd6-26a1-4edb-ae67-cac5bcd9ed6a"
game_objects = [{ name = "Posters" }]

[[block]]
friendly_name = "Pocket Storm"
world_id = "wrld_4c64a2fa-2916-4491-8764-11221af96f98"
game_objects = [{ name = "ads (1) Variant" }]

[[block]]
friendly_name = "Just B Club 3"
world_id = "wrld_e6569266-21cd-4275-8aef-47fcb7458931"
game_objects = [
    { name = "Discord TV Ad (2)" },
    { name = "TV vertical" },
    { name = "TV vertical (3)" },
    { name = "TV vertical (4)" },
    { name = "TV vertical (5)" },
    { name = "TV vertical (6)" },
    { name = "TV vertical (7)" },
    { name = "TV vertical (8)" },
    { name = "TV vertical (9)" },
    { name = "TV vertical (10)" },
    { name = "TV Prefab UNIQUE", position = { x = -4.3660707, y = 3.0724978, z = -58.21133 } },
]

[[block]]
friendly_name = "Avatar Testing Chamber"
world_id = "wrld_a5e9ec13-36b1-4e63-ae0c-dab9023401f9"
game_objects = [
    { name = "Neverphone" }
]

[[block]]
friendly_name = "The room of the rain"
world_id = "wrld_fae3fa95-bc18-46f0-af57-f0c97c0ca90a"
game_objects = [
    { name = "Neverphone" }, # removes the phone
    { name = "Horizontal_poster"}, # removes the horizontal nevermet poster
    { name = "Quad (1)"} # removes the vertical SlimeVR poster
]