title = "AdGoBye Ads"
description = "Base Ads Blocklist made by AGB Team"
maintainer = "https://zombo.com"

[[block]]
friendly_name = "LSMedia"
world_id = "wrld_1b68f7a8-8aea-4900-b7a2-3fc4139ac817"
game_objects = [{ name = "ADs" }]

[[block]]
friendly_name = "Movie & Chill"
world_id = "wrld_791ebf58-54ce-4d3a-a0a0-39f10e1b20b2"
game_objects = [
    { name = "PosterManager" },
    { name = "PhotoViewer" },
    { name = "PhotoViewer (1)" },
    { name = "PhotoViewer (2)" },
    { name = "PhotoViewer (3)" }
]

[[block]]
friendly_name = "Sovren's Chill home"
world_id = "wrld_1b482eca-bede-4de8-88a8-bbb6ca7e24cd"
game_objects = [
    { name = "add board" },
    { name = "InsetPosterDarkVerticalBlack_04" }
]

[[block]]
friendly_name = "Default Home"
world_id = "wrld_4432ea9b-729c-46e3-8eaf-846aa0a37fdd"
game_objects = [
    { name = "posterlight (10)" },
    # Plush advertisements, remove when promption ends
    { name = "_Details_Core_MS2023" },
    { name = "ACTUAL_SIZE" }
]

[[block]]
friendly_name = "SunDown"
world_id = "wrld_c54add9f-29b2-4b60-b051-e4999966ebc8"
game_objects = [{ name = "Promotional" }]

[[block]]
friendly_name = "Midnight Rooftop"
world_id = "wrld_d29bb0d0-d268-42dc-8365-926f9d485505"
game_objects = [
    { name = "Stairwell_Billboard_Nevermet" },
    { name = "Nevermet Hostess Functionality" },
    { name = "SpawnHallway_Posters" },
    { name = "Nevermet Distance Disable" },
    # Spawn Hallway Wall Lamps
    { name = "Leukon_Wall (4)" },
    { name = "Leukon_Wall (5)" },
    { name = "Leukon_Wall (6)" },
    { name = "Leukon_Wall (7)" },
    { name = "Leukon_Wall (8)" },
    { name = "Leukon_Wall (9)" },
    { name = "Leukon_Wall (10)" },
    { name = "Leukon_Wall (11)" },
    { name = "Leukon_Wall (12)" },
    { name = "Leukon_Wall (13)" },
    { name = "Leukon_Wall (14)" },
    { name = "Leukon_Wall (15)" },
    # Networked ads
    { name = "Stairwell_Billboard_Ad" },
    { name = "Bar_Billboard_Ad" },
    { name = "Bar_Billboard_NoneAd" },
    { name = "Stairwell_Billboard_NoneAd" }
]

[[block]]
friendly_name = "Furry Hideout"
world_id = "wrld_4b341546-65ff-4607-9d38-5b7f8f405132"
game_objects = [
    { name = "MeshBaker (0)-mesh-mesh (2)", position = { x = 78.925, y = -70.151, z = -128.275 } },
    { name = "MeshBaker (0)-mesh-mesh", position = { x = -0.043, y = 0.013, z = 0.03299999 } },
    { name = "MeshBaker (0)-mesh-mesh (1)", position = { x = 151.96, y = 102.675, z = -275.02 } },
    { name = "Cube (9)" }
]

[[block]]
friendly_name = "Prison Escape!"
world_id = "wrld_14750dd6-26a1-4edb-ae67-cac5bcd9ed6a"
game_objects = [{ name = "Posters" }]

[[block]]
friendly_name = "Pocket Storm"
world_id = "wrld_4c64a2fa-2916-4491-8764-11221af96f98"
game_objects = [{ name = "ads (1) Variant" }]

[[block]]
friendly_name = "Just B Club 3"
world_id = "wrld_e6569266-21cd-4275-8aef-47fcb7458931"
game_objects = [
    { name = "Discord TV Ad (2)" },
    { name = "TV vertical" },
    { name = "TV vertical (3)" },
    { name = "TV vertical (4)" },
    { name = "TV vertical (5)" },
    { name = "TV vertical (6)" },
    { name = "TV vertical (7)" },
    { name = "TV vertical (8)" },
    { name = "TV vertical (9)" },
    { name = "TV vertical (10)" },
    { name = "TV Prefab UNIQUE", position = { x = -4.366071, y = 3.072498, z = -58.21133 } }
]

[[block]]
friendly_name = "Vket2023W Parareal London"
world_id = "wrld_9eb712f4-4305-4d19-8c74-47835730ecbf"
game_objects = [
    { name = "Nevermet Host Functionality" },
    { name = "Nevermet" }
]

[[block]]
friendly_name = "Avatar Testing Chamber"
world_id = "wrld_a5e9ec13-36b1-4e63-ae0c-dab9023401f9"
game_objects = [
    { name = "Neverphone" }
]