title = "AdGoBye Community Ads"
description = "Ads / Posters which are related to a specific world or community in that world (such as events or socials)"
maintainer = "https://zombo.com"

[[block]]
friendly_name = "Movie & Chill"
world_id = "wrld_791ebf58-54ce-4d3a-a0a0-39f10e1b20b2"
game_objects = [{ name = "Label (2)" }]

[[block]]
friendly_name = "The Black Cat"
world_id = "wrld_4cf554b4-430c-4f8f-b53e-1f294eed230b"
game_objects = [
    { name = "cork medium", position = { x = 26.773, y = 3.244, z = -13.982 } },
    { name = "Join Group", position = { x = 0, y = 0, z = -7.607 } },
    { name = "SGB Corkboard" },
    { name = "POS" }
]

[[block]]
friendly_name = "Furry Hideout"
world_id = "wrld_4b341546-65ff-4607-9d38-5b7f8f405132"
game_objects = [
    { name = "PPSUI (2)" },
    { name = "Cube (5)", position = {x = -29.597, y = 44.894, z = 6.501}},
    { name = "Ui Board (1)", position = {x = 0, y = 0, z = 21.106989}}
]

[[block]]
friendly_name = "Furry Talk and Chill"
world_id = "wrld_e76f0ce1-8b2f-4fd7-a6ac-84443d6f26f1"
game_objects = [{ name = "Bottom Tex" }] # actual object name

[[block]]
friendly_name = "Murder 4"
world_id = "wrld_858dfdfc-1b48-4e1e-8a43-f0edc611e5fe"
game_objects = [{ name = "Link (2)" }]

[[block]]
friendly_name = "Prison Escape!"
world_id = "wrld_14750dd6-26a1-4edb-ae67-cac5bcd9ed6a"
game_objects = [
    { name = "Creator Sign"},
    { name = "Creator Sign (1)"}
]

[[block]]
friendly_name = "Just B Club 3"
world_id = "wrld_e6569266-21cd-4275-8aef-47fcb7458931"
game_objects = [
    { name = "Discord TV Ad (1)" },
    { name = "TV Prefab UNIQUE", position = { x = -4.366071, y = 3.072498, z = -54.21133 } },
    { name = "Poster (9)", parent = { name = "Poster (9)" } }
]