title = "AdGoBye Supporters"
description = "Supporter walls / elements"
maintainer = "https://zombo.com"

[[block]]
friendly_name = "LSMedia"
world_id = "wrld_1b68f7a8-8aea-4900-b7a2-3fc4139ac817"
game_objects = [
    { name = "BillBoard" },
    { name = "Supporter Names" },
    { name = "Supporter Names2" },
    { name = "Supporters_Images" }
]

[[block]]
friendly_name = "Movie & Chill"
world_id = "wrld_791ebf58-54ce-4d3a-a0a0-39f10e1b20b2"
game_objects = [{ name = "Canvas" }]

[[block]]
friendly_name = "The Black Cat"
world_id = "wrld_4cf554b4-430c-4f8f-b53e-1f294eed230b"
game_objects = [
    { name = "PATREON" },
    { name = "plaque" },
    { name = "plaque (1)" },
    { name = "plaque (2)" },
    { name = "Plaque Thank you" },
    { name = "Plaque Thank you (1)" },
    { name = "Plaque Thank you (2)" }
]

[[block]]
friendly_name = "Furry Hideout"
world_id = "wrld_4b341546-65ff-4607-9d38-5b7f8f405132"
game_objects = [
    { name = "Links" },
]

[[block]]
friendly_name = "Murder 4"
world_id = "wrld_858dfdfc-1b48-4e1e-8a43-f0edc611e5fe"
game_objects = [{ name = "Patreon Canvas" }]

[[block]]
friendly_name = "Prison Escape!"
world_id = "wrld_14750dd6-26a1-4edb-ae67-cac5bcd9ed6a"
game_objects = [{name = "Patrons Sign"}]