title = "AdGoBye Supporters"
description = "World supporter boards or supporter images"
maintainer = "https://zombo.com"

[[block]]
friendly_name = "LSMedia"
world_id = "wrld_f767d1c8-b249-4ecc-a56f-614e433682c8"
game_objects = [
    { name = "Supporters_Images" },
    { name = "BillBoard" },
]

[[block]]
friendly_name = "The room of the rain"
world_id = "wrld_fae3fa95-bc18-46f0-af57-f0c97c0ca90a"
game_objects = [
    { name = "Patreon ui", parent = { name = "Patreon Things" } }, # removes the UI with patreon only settings
    { name = "Patreon panel", parent = { name = "Patreon Things" } }, # removes the auto scrolling image board of patreon subscribers
    { name = "Patreon texture Changer", parent = { name = "Patreon Things" } }, # removes texture changer for the patreon panel to avoid Udon exceptions for missing refrences
    { name = "Patreon texture Changer (1)", parent = { name = "Patreon Things" } },
]

[[block]]
friendly_name = "The Black Cat"
world_id = "wrld_4cf554b4-430c-4f8f-b53e-1f294eed230b"
game_objects = [
    { name = "plaque" },
    { name = "Contributor Name Canvas" }
]

[[block]]
friendly_name = "Sovren's Chill home"
world_id = "wrld_1b482eca-bede-4de8-88a8-bbb6ca7e24cd"
game_objects = [
    { name = "patreon frames" },
]

[[block]]
friendly_name = "Midnight Rooftop"
world_id = "wrld_d29bb0d0-d268-42dc-8365-926f9d485505"
game_objects = [
    { name = "SupporterBillboard_GroupA_01" },
    { name = "SupporterBillboard_GroupA_02" },
    { name = "SupporterBillboard_GroupB_01" },
    { name = "SupporterBillboard_GroupB_02" },
    { name = "PatreonLists"}
]

[[block]]
friendly_name = "Furry Hideout"
world_id = "wrld_4b341546-65ff-4607-9d38-5b7f8f405132"
game_objects = [
    { name = "SupporterListPrefabAutoScrolling 1"},
    { name = "RoleBoardV2"},
    { name = "Links"}
]

[[block]]
friendly_name = "Prison Escape!"
world_id = "wrld_14750dd6-26a1-4edb-ae67-cac5bcd9ed6a"
game_objects = [
    {name = "Patrons Sign"}
]

[[block]]
friendly_name = "Pocket Storm"
world_id = "wrld_4c64a2fa-2916-4491-8764-11221af96f98"
game_objects = [
    {name = "GameObject", parent = {name = "Panel3"}}
]

[[block]]
friendly_name = "Just B Club 3"
world_id = "wrld_e6569266-21cd-4275-8aef-47fcb7458931"
game_objects = [
    # UI dynamically renabled here, so we'll need to disable the children instead.
    { name = "Panel", parent =  { name = "2.0 Patreon Canvas" } },
]

[[block]]
friendly_name = "VirtualFurence Furry Convention Hotel Estrel Berlin"
world_id = "wrld_b155ff30-0bbf-486c-afc5-e7a05145387b"
game_objects = [{ name = "SupporterList" }]

[[block]]
friendly_name = "Zombie Survival"
world_id = "wrld_f557959f-6fde-4164-be36-31f1d40bb9a5"
game_objects = [
    { name = "Scroll View" },
]

[[block]]
friendly_name = "Murder 4"
world_id = "wrld_858dfdfc-1b48-4e1e-8a43-f0edc611e5fe"
game_objects = [
    { name = "Patreon Canvas" }
]

[[block]]
friendly_name = "GeoLocator Remapped"
world_id = "wrld_8abba687-ebfd-4356-846d-d069976df375"
game_objects = [{ name = "PatreonBoard" }]

[[block]]
friendly_name = "Popcorn Palace"
world_id = "wrld_266523e8-9161-40da-acd0-6bd82e075833"
game_objects = [
    {name = "Patreon Canvas"}
]